#!/bin/sh
#
# Wrapper script for winetricks compatability
#
# Copyright (C) 2018-2023 Dean M Greer
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
#

# workaround SIP DYLD_stripping
# see https://support.apple.com/en-us/HT204899
export WINETRICKS_FALLBACK_LIBRARY_PATH="${WINETRICKS_FALLBACK_LIBRARY_PATH:-$(dirname "$0")/../../../Contents/Frameworks}"
export DYLD_FALLBACK_LIBRARY_PATH="${WINETRICKS_FALLBACK_LIBRARY_PATH}"
export WINESKINPATH="$(dirname "$0")/../../../Contents/SharedSupport/wine/bin"
export WINEPREFIX="${WINEPREFIX:-$(dirname "$0")/../../../Contents/SharedSupport/prefix}"

# Pre macOS Catalina check for wine and use if found
if [[ ${OSTYPE:6} -lt 19 && -x "$(command -v "$WINESKINPATH"/wine)" ]]; then exec "$WINESKINPATH/wine" "${@}"; fi

# macOS Catalina or greater check for wine32on64 and use if found (CX19-CX21)
if [[ ${OSTYPE:6} -ge 19 && -x "$(command -v "$WINESKINPATH"/wine32on64)" ]]; then exec "$WINESKINPATH/wine32on64" "${@}"; fi

# Check for wine64 and use if found, fallback incase of wow64 or 64Bit only Engine
if [[ -x "$(command -v "$WINESKINPATH"/wine64)" ]]; then exec "$WINESKINPATH/wine64" "${@}"; fi

echo "Error: the wine loader was not found in $WINESKINPATH"
exit 1
