#!/bin/bash
###################################################
#  CustomEXE code for Wineskin wrappers
#  Made by doh123@doh123.com
#
#  Version 5.0
#
#  This code is Open Source and licensed under the
#  terms of the GNU Lesser General Public License.
#  If the License file is not with this script, the
#  full license can be read at the following URL
#
#  http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html
#
#  For Wineskin information, see the project website at
#  http://wineskin.doh123.com
#
####################################################
# Set all variables
CFRAMEBINFOLD="$(dirname "$0")"
FRAMEBINFOLD="$CFRAMEBINFOLD/../../../Contents/Frameworks/bin"
cd "$FRAMEBINFOLD"
FRAMEBINFOLD="$(echo "$PWD")"
CEXENAME="$(basename "${CFRAMEBINFOLD%/Contents/MacOS}")"

# Launch wrapper
"$FRAMEBINFOLD/Wineskin" "CustomEXE" "$CEXENAME"
